services:
    ros2_dev:
        image: ros2_dev_test
        container_name: ros2_dev_test
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/root/ros2_docker_test

        stdin_open: true
        tty: true